// Auto-generated file - do not edit manually
// Generated by generate-markdown-imports.js

export interface CuadernilloContent {
  dialogue: string;
  conjugation: string;
  choice: string;
  transformation: string;
  ordering: string;
  evaluation: string;
}

export const markdownContent: Record<string, Record<string, Record<string, CuadernilloContent>>> = {
  'present-tense': {
    '1': {
      'japanese': {
        dialogue: `# 会話

## 家で (En casa de María)

**María:** ¡Hola, Luis! ¿Qué haces?

**Luis:** Hola, María. Yo **dibujo** un perro. ¿Te gusta?

**María:** ¡Sí! **Dibujas** muy bien. Yo **busco** mi libro de matemáticas.

**Luis:** ¿**Estudias** mucho?

**María:** Sí, **estudio** todos los días. Mis padres **hablan** conmigo sobre mis notas.

**Luis:** Mis padres también **hablan** conmigo sobre la escuela.

**María:** ¿Tú qué haces después de **estudiar**?

**Luis:** **Dibujar** o jugar. ¿Y tú?

**María:** Yo **bailo**. Me gusta mucho **bailar**.
`,
        conjugation: `# 現在形 - 動詞 HABLAR (話す)

| yo            | hablo  | nosotros/nosotras   | hablamos |
| ------------- | ------ | ------------------- | -------- |
| tú            | hablas | vosotros/vosotras   | habláis  |
| él/ella/usted | habla  | ellos/ellas/ustedes | hablan   |

**例文:** Yo hablo español en casa con mi familia.

## 正しい形で空欄を埋めてください:

**1.** Yo [SHORT_LINE] (dibujar) un gato en mi cuaderno.

**2.** Tú [SHORT_LINE] (buscar) tu mochila en la clase.

**3.** Ella [SHORT_LINE] (bailar) muy bien en las fiestas.

**4.** Nosotros [SHORT_LINE] (hablar) japonés en la escuela.

**5.** Ellos [SHORT_LINE] (dibujar) flores en el jardín.

**6.** Vosotros [SHORT_LINE] (bailar) flamenco los viernes.

**7.** Usted [SHORT_LINE] (buscar) trabajo en la ciudad.

**8.** Mis hermanos [SHORT_LINE] (hablar) con sus amigos.

**9.** Tú [SHORT_LINE] (dibujar) muy bien los animales.

**10.** Nosotras [SHORT_LINE] (buscar) un regalo para mamá.
`,
        choice: `# 正しい形を選んで完全な文を書いてください:

**1.** Mi hermana [baila | bailas] flamenco los martes.

   [LONG_LINE]

**2.** Los estudiantes [buscan | buscáis] información en la biblioteca.

   [LONG_LINE]

**3.** Tú [hablas | habla] muy rápido cuando estás nervioso.

   [LONG_LINE]

**4.** El artista [dibujo | dibuja] retratos increíbles.

   [LONG_LINE]

**5.** Nosotros [bailamos | bailan] salsa en la academia.

   [LONG_LINE]

**6.** Las niñas [busca | buscan] conchas en la playa.

   [LONG_LINE]

**7.** Vosotros [dibujáis | dibujan] mapas en geografía.

   [LONG_LINE]

**8.** El profesor [habla | hablan] muy claro en clase.

   [LONG_LINE]`,
        transformation: `# 指示に従って動詞の人称を変えてください:

**1.** Yo dibujo → Nosotros [SHORT_LINE]

**2.** Tú hablas → Él [SHORT_LINE]

**3.** Ella baila → Ellas [SHORT_LINE]

**4.** Nosotros buscamos → Yo [SHORT_LINE]

**5.** Vosotros bailáis → Tú [SHORT_LINE]

**6.** Él habla → Nosotros [SHORT_LINE]

**7.** Ellas dibujan → Ella [SHORT_LINE]

**8.** Yo busco → Vosotros [SHORT_LINE]

## 質問に答えてください:

**1.** ¿Tú dibujas animales? → Sí, yo [SHORT_LINE] animales.

**2.** ¿Ellos buscan trabajo? → Sí, ellos [SHORT_LINE] trabajo.

**3.** ¿Vosotros bailáis salsa? → Sí, nosotros [SHORT_LINE] salsa.

**4.** ¿Ella habla japonés? → Sí, ella [SHORT_LINE] japonés.

**5.** ¿Ustedes dibujan bien? → Sí, nosotros [SHORT_LINE] bien.`,
        ordering: `# 単語を並べ替えて正しい文を作ってください:

**1.** [muy / Mi / baila / bien / hermano]

私の兄はとても上手に踊ります。

[LONG_TALL_LINE]

**2.** [en / hablan / Los / español / niños / casa]

子供たちは家でスペイン語を話します。

[LONG_TALL_LINE]

**3.** [flores / Él / dibuja / jardín / del]

彼は庭の花を描きます。

[LONG_TALL_LINE]

**4.** [sus / Nosotros / llaves / buscamos]

私たちは鍵を探します。

[LONG_TALL_LINE]

**5.** [salsa / Tú / los / bailas / sábados]

君は土曜日にサルサを踊ります。

[LONG_TALL_LINE]

**6.** [francés / Ella / también / habla]

彼女はフランス語も話します。

[LONG_TALL_LINE]
`,
        evaluation: `# 文を読んで、正しければB、間違っていればMを書き、間違いを訂正してください:

**1.** Yo hablas con mi profesora. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**2.** Los pájaros buscan comida en el parque. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**3.** Tú dibujas mapas en geografía. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**4.** Nosotros baila en el gimnasio. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**5.** Mi gato busca ratones en la casa. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**6.** Vosotros habláis muy alto en clase. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**7.** Ellas baila en la discoteca. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**8.** Tú busca tus llaves en el bolso. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]`,
      },
      'english': {
        dialogue: `# Dialogue

## At home (En casa de María)

**María:** ¡Hola, Luis! ¿Qué haces?

**Luis:** Hola, María. Yo **dibujo** un perro. ¿Te gusta?

**María:** ¡Sí! **Dibujas** muy bien. Yo **busco** mi libro de matemáticas.

**Luis:** ¿**Estudias** mucho?

**María:** Sí, **estudio** todos los días. Mis padres **hablan** conmigo sobre mis notas.

**Luis:** Mis padres también **hablan** conmigo sobre la escuela.

**María:** ¿Tú qué haces después de **estudiar**?

**Luis:** **Dibujar** o jugar. ¿Y tú?

**María:** Yo **bailo**. Me gusta mucho **bailar**.
`,
        conjugation: `# Present tense - Verb HABLAR (to speak / to talk)

| yo            | hablo  | nosotros/nosotras   | hablamos |
| ------------- | ------ | ------------------- | -------- |
| tú            | hablas | vosotros/vosotras   | habláis  |
| él/ella/usted | habla  | ellos/ellas/ustedes | hablan   |

**Example (Ejemplo):** Yo hablo español en casa con mi familia.

## Complete the sentences with the correct verb form:

**1.** Yo [SHORT_LINE] (dibujar) un gato en mi cuaderno.

**2.** Tú [SHORT_LINE] (buscar) tu mochila en la clase.

**3.** Ella [SHORT_LINE] (bailar) muy bien en las fiestas.

**4.** Nosotros [SHORT_LINE] (hablar) japonés en la escuela.

**5.** Ellos [SHORT_LINE] (dibujar) flores en el jardín.

**6.** Vosotros [SHORT_LINE] (bailar) flamenco los viernes.

**7.** Usted [SHORT_LINE] (buscar) trabajo en la ciudad.

**8.** Mis hermanos [SHORT_LINE] (hablar) con sus amigos.

**9.** Tú [SHORT_LINE] (dibujar) muy bien los animales.

**10.** Nosotras [SHORT_LINE] (buscar) un regalo para mamá.
`,
        choice: `# Choose the correct form and write the complete sentence:

**1.** Mi hermana [baila | bailas] flamenco los martes.

   [LONG_LINE]

**2.** Los estudiantes [buscan | buscáis] información en la biblioteca.

   [LONG_LINE]

**3.** Tú [hablas | habla] muy rápido cuando estás nervioso.

   [LONG_LINE]

**4.** El artista [dibujo | dibuja] retratos increíbles.

   [LONG_LINE]

**5.** Nosotros [bailamos | bailan] salsa en la academia.

   [LONG_LINE]

**6.** Las niñas [busca | buscan] conchas en la playa.

   [LONG_LINE]

**7.** Vosotros [dibujáis | dibujan] mapas en geografía.

   [LONG_LINE]

**8.** El profesor [habla | hablan] muy claro en clase.

   [LONG_LINE]`,
        transformation: `# Change the person of the verb as indicated:

**1.** Yo dibujo → Nosotros [SHORT_LINE]

**2.** Tú hablas → Él [SHORT_LINE]

**3.** Ella baila → Ellas [SHORT_LINE]

**4.** Nosotros buscamos → Yo [SHORT_LINE]

**5.** Vosotros bailáis → Tú [SHORT_LINE]

**6.** Él habla → Nosotros [SHORT_LINE]

**7.** Ellas dibujan → Ella [SHORT_LINE]

**8.** Yo busco → Vosotros [SHORT_LINE]

## Answer the questions:

**1.** ¿Tú dibujas animales? → Sí, yo [SHORT_LINE] animales.

**2.** ¿Ellos buscan trabajo? → Sí, ellos [SHORT_LINE] trabajo.

**3.** ¿Vosotros bailáis salsa? → Sí, nosotros [SHORT_LINE] salsa.

**4.** ¿Ella habla japonés? → Sí, ella [SHORT_LINE] japonés.

**5.** ¿Ustedes dibujan bien? → Sí, nosotros [SHORT_LINE] bien.`,
        ordering: `# Put the words in the correct order to form sentences:

**1.** [muy / Mi / baila / bien / hermano]

   My brother dances very well

   [LONG_TALL_LINE]

**2.** [en / hablan / Los / español / niños / casa]

   The children speak Spanish at home

   [LONG_TALL_LINE]

**3.** [flores / El / dibuja / jardín / del]

   He draws flowers from the garden

   [LONG_TALL_LINE]

**4.** [sus / Nosotros / llaves / buscamos]

   We look for our keys

   [LONG_TALL_LINE]

**5.** [salsa / Tú / los / bailas / sábados]

   You dance salsa on Saturdays

   [LONG_TALL_LINE]

**6.** [francés / Ella / también / habla]

   She also speaks French

   [LONG_TALL_LINE]`,
        evaluation: `# Read the sentences. If correct, write R. If incorrect, write W and correct it below:

**1.** Yo hablas con mi profesora. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**2.** Los pájaros buscan comida en el parque. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**3.** Tú dibujas mapas en geografía. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**4.** Nosotros baila en el gimnasio. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**5.** Mi gato busca ratones en la casa. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**6.** Vosotros habláis muy alto en clase. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**7.** Ellas baila en la discoteca. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**8.** Tú busca tus llaves en el bolso. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]`,
      },
    },
    '2': {
      'japanese': {
        dialogue: `# 会話

## キッチンで (En la cocina)

**Pedro:** ¡Mamá! ¿Qué **comes**?

**Mamá:** **Como** una manzana, Pedro. ¿Tienes hambre?

**Pedro:** Sí. Nosotros **comemos** muy tarde hoy.

**Mamá:** Es verdad. Papá **lee** el periódico y no ve la hora.

**Pedro:** Él siempre **lee** después del trabajo.

**Mamá:** Sí, le gusta **leer**. ¿Tú qué haces?

**Pedro:** Yo **aprendo** nuevas palabras en español.

**Mamá:** Muy bien. **Aprendes** cada día, ¿verdad?

**Pedro:** Sí, **aprendo** algo nuevo todas las tardes.
`,
        conjugation: `# 現在形 - 動詞 COMER (食べる)

| yo            | como  | nosotros/nosotras   | comemos |
| ------------- | ----- | ------------------- | ------- |
| tú            | comes | vosotros/vosotras   | coméis  |
| él/ella/usted | come  | ellos/ellas/ustedes | comen   |

**例文:** Yo como frutas y verduras todos los días.

## 正しい形で空欄を埋めてください:

**1.** Yo [SHORT_LINE] (leer) libros de aventuras.

**2.** Tú [SHORT_LINE] (aprender) español muy rápido.

**3.** Ella [SHORT_LINE] (beber) agua después del deporte.

**4.** Nosotros [SHORT_LINE] (comer) en el comedor de la escuela.

**5.** Ellos [SHORT_LINE] (leer) el mismo libro para clase.

**6.** Vosotros [SHORT_LINE] (comer) paella en el restaurante.

**7.** Usted [SHORT_LINE] (beber) café todas las mañanas.

**8.** Mis padres [SHORT_LINE] (aprender) inglés en la academia.

**9.** Tú [SHORT_LINE] (comer) verduras en la cena.

**10.** Nosotras [SHORT_LINE] (leer) revistas en la biblioteca.
`,
        choice: `# 正しい形を選んで完全な文を書いてください:

**1.** Mi padre [lee | lees] el periódico cada mañana.

   [LONG_LINE]

**2.** Los niños [beben | bebéis] leche en el desayuno.

   [LONG_LINE]

**3.** Tú [aprendes | aprende] matemáticas con tu hermana.

   [LONG_LINE]

**4.** La profesora [como | come] en la sala de profesores.

   [LONG_LINE]

**5.** Nosotros [leemos | leen] cuentos antes de dormir.

   [LONG_LINE]

**6.** Las hermanas [aprenden | aprendéis] francés en la escuela.

   [LONG_LINE]

**7.** Vosotros [coméis | comen] tapas en el bar.

   [LONG_LINE]

**8.** El médico [bebe | beben] té verde después de comer.

   [LONG_LINE]`,
        transformation: `# 指示に従って動詞の人称を変えてください:

**1.** Yo como → Nosotros [SHORT_LINE]

**2.** Tú lees → Él [SHORT_LINE]

**3.** Ella aprende → Ellas [SHORT_LINE]

**4.** Nosotros bebemos → Yo [SHORT_LINE]

**5.** Vosotros coméis → Tú [SHORT_LINE]

**6.** Él aprende → Nosotros [SHORT_LINE]

**7.** Ellas leen → Ella [SHORT_LINE]

**8.** Yo bebo → Vosotros [SHORT_LINE]

## 質問に答えてください:

**1.** ¿Tú lees novelas? → Sí, yo [SHORT_LINE] novelas.

**2.** ¿Ellos comen pescado? → Sí, ellos [SHORT_LINE] pescado.

**3.** ¿Vosotros bebéis café? → Sí, nosotros [SHORT_LINE] café.

**4.** ¿Ella aprende inglés? → Sí, ella [SHORT_LINE] inglés.

**5.** ¿Ustedes comen verduras? → Sí, nosotros [SHORT_LINE] verduras.`,
        ordering: `# 単語を並べ替えて正しい文を作ってください:

**1.** [mucha / Mi / agua / bebe / hermana]

私の姉は水をたくさん飲みます。

[LONG_TALL_LINE]

**2.** [en / aprenden / Los / inglés / estudiantes / casa]

学生たちは家で英語を学びます。

[LONG_TALL_LINE]

**3.** [chocolate / come / El / niño]

男の子はチョコレートを食べます。

[LONG_TALL_LINE]

**4.** [periódico / el / leemos / los / Nosotros / domingos]

私たちは日曜日に新聞を読みます。

[LONG_TALL_LINE]

**5.** [té / Tú / caliente / bebes]

君は熱いお茶を飲みます。

[LONG_TALL_LINE]

**6.** [cartas / Ella / largas / escribe]

彼女は長い手紙を書きます。

[LONG_TALL_LINE]
`,
        evaluation: `# 文を読んで、正しければB、間違っていればMを書き、間違いを訂正してください:

**1.** Yo comes pan en el desayuno. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**2.** Los gatos beben leche del plato. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**3.** Tú lee libros en la biblioteca. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**4.** Nosotros aprendemos español en casa. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**5.** Mi hermano come verduras en la cena. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**6.** Vosotros bebéis zumo de naranja. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**7.** Ellas come chocolate en el recreo. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**8.** Tú aprender música en el conservatorio. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]`,
      },
      'english': {
        dialogue: `# Dialogue

## In the kitchen (En la cocina)

**Pedro:** ¡Mamá! ¿Qué **comes**?

**Mamá:** **Como** una manzana, Pedro. ¿Tienes hambre?

**Pedro:** Sí. Nosotros **comemos** muy tarde hoy.

**Mamá:** Es verdad. Papá **lee** el periódico y no ve la hora.

**Pedro:** Él siempre **lee** después del trabajo.

**Mamá:** Sí, le gusta **leer**. ¿Tú qué haces?

**Pedro:** Yo **aprendo** nuevas palabras en español.

**Mamá:** Muy bien. **Aprendes** cada día, ¿verdad?

**Pedro:** Sí, **aprendo** algo nuevo todas las tardes.
`,
        conjugation: `# Present tense - Verb COMER (to eat)

| yo            | como  | nosotros/nosotras   | comemos |
| ------------- | ----- | ------------------- | ------- |
| tú            | comes | vosotros/vosotras   | coméis  |
| él/ella/usted | come  | ellos/ellas/ustedes | comen   |

**Example (Ejemplo):** Yo como frutas y verduras todos los días.

## Complete the sentences with the correct verb form:

**1.** Yo [SHORT_LINE] (leer) libros de aventuras.

**2.** Tú [SHORT_LINE] (aprender) español muy rápido.

**3.** Ella [SHORT_LINE] (beber) agua después del deporte.

**4.** Nosotros [SHORT_LINE] (comer) en el comedor de la escuela.

**5.** Ellos [SHORT_LINE] (leer) el mismo libro para clase.

**6.** Vosotros [SHORT_LINE] (beber) zumo de naranja.

**7.** Usted [SHORT_LINE] (aprender) inglés en la academia.

**8.** Mis hermanas [SHORT_LINE] (comer) frutas cada día.

**9.** Tú [SHORT_LINE] (leer) muy rápido los periódicos.

**10.** Nosotras [SHORT_LINE] (aprender) canciones nuevas.
`,
        choice: `# Choose the correct form and write the complete sentence:

**1.** Mi padre [lee | lees] el periódico cada mañana.

   [LONG_LINE]

**2.** Los niños [beben | bebéis] leche en el desayuno.

   [LONG_LINE]

**3.** Tú [aprendes | aprende] matemáticas con tu hermana.

   [LONG_LINE]

**4.** La profesora [como | come] en la sala de profesores.

   [LONG_LINE]

**5.** Nosotros [leemos | leen] cuentos antes de dormir.

   [LONG_LINE]

**6.** Las hermanas [aprenden | aprendéis] francés en la escuela.

   [LONG_LINE]

**7.** Vosotros [coméis | comen] tapas en el bar.

   [LONG_LINE]

**8.** El médico [bebe | beben] té verde después de comer.

   [LONG_LINE]`,
        transformation: `# Change the person of the verb as indicated:

**1.** Yo como → Nosotros [SHORT_LINE]

**2.** Tú lees → Él [SHORT_LINE]

**3.** Ella aprende → Ellas [SHORT_LINE]

**4.** Nosotros bebemos → Yo [SHORT_LINE]

**5.** Vosotros coméis → Tú [SHORT_LINE]

**6.** Él bebe → Nosotros [SHORT_LINE]

**7.** Ellas leen → Ella [SHORT_LINE]

**8.** Yo aprendo → Vosotros [SHORT_LINE]

## Answer the questions:

**1.** ¿Tú lees novelas? → Sí, yo [SHORT_LINE] novelas.

**2.** ¿Ellos comen pescado? → Sí, ellos [SHORT_LINE] pescado.

**3.** ¿Vosotros bebéis café? → Sí, nosotros [SHORT_LINE] café.

**4.** ¿Ella aprende francés? → Sí, ella [SHORT_LINE] francés.

**5.** ¿Ustedes comen verduras? → Sí, nosotros [SHORT_LINE] verduras.`,
        ordering: `# Put the words in the correct order to form sentences:

**1.** [mucha / Mi / agua / bebe / hermana]

   My sister drinks a lot of water

   [LONG_TALL_LINE]

**2.** [en / aprenden / Los / inglés / estudiantes / casa]

   The students learn English at home

   [LONG_TALL_LINE]

**3.** [chocolate / come / El / niño]

   The boy eats chocolate

   [LONG_TALL_LINE]

**4.** [periódicos / leemos / los / Nosotros / domingos]

   We read newspapers on Sundays

   [LONG_TALL_LINE]

**5.** [té / Tú / caliente / bebes]

   You drink hot tea

   [LONG_TALL_LINE]

**6.** [cartas / Ella / largas / escribe]

   She writes long letters

   [LONG_TALL_LINE]`,
        evaluation: `# Read the sentences. If correct, write R. If incorrect, write W and correct:

**1.** Yo comes pan en el desayuno. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**2.** Los gatos beben leche del plato. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**3.** Tú lee libros en la biblioteca. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**4.** Nosotros aprendemos español en casa. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**5.** Mi hermano come verduras en la cena. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**6.** Vosotros bebéis zumo de naranja. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**7.** Ellas come pescado los viernes. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**8.** Tú aprende matemáticas rápido. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]`,
      },
    },
    '3': {
      'japanese': {
        dialogue: `# 会話

## 庭で (En el jardín)

**Laura:** ¡Qué bonitas flores! ¿Tú las cuidas?

**Diego:** Sí, yo **vivo** aquí con mis abuelos. Ellos tienen un jardín grande.

**Laura:** ¿**Vives** aquí todo el año?

**Diego:** Sí, **vivo** aquí desde el año pasado. Me gusta mucho.

**Laura:** Mis abuelos también **viven** en una casa con jardín.

**Diego:** ¿Ellos cuidan plantas también?

**Laura:** No, pero mi abuela **escribe** sobre jardines en su blog.

**Diego:** ¡Qué interesante! ¿Tú también **escribes**?

**Laura:** Un poco. **Escribo** en mi diario todas las noches.
`,
        conjugation: `# 現在形 - 動詞 VIVIR (住む)

| yo            | vivo  | nosotros/nosotras   | vivimos |
| ------------- | ----- | ------------------- | ------- |
| tú            | vives | vosotros/vosotras   | vivís   |
| él/ella/usted | vive  | ellos/ellas/ustedes | viven   |

**例文:** Yo vivo en una casa cerca de la escuela.

## 正しい形で空欄を埋めてください:

**1.** Yo [SHORT_LINE] (escribir) postales a mis amigos.

**2.** Tú [SHORT_LINE] (abrir) la ventana cuando hace calor.

**3.** Ella [SHORT_LINE] (vivir) en el centro de la ciudad.

**4.** Nosotros [SHORT_LINE] (subir) las escaleras todos los días.

**5.** Ellos [SHORT_LINE] (escribir) sus nombres en la lista.

**6.** Vosotros [SHORT_LINE] (vivir) cerca del parque.

**7.** Usted [SHORT_LINE] (abrir) la tienda a las nueve.

**8.** Mis abuelos [SHORT_LINE] (subir) despacio las escaleras.

**9.** Tú [SHORT_LINE] (escribir) cartas a tus amigos.

**10.** Nosotras [SHORT_LINE] (vivir) en el mismo barrio.
`,
        choice: `# 正しい形を選んで完全な文を書いてください:

**1.** Mi hermano [vive | vives] en el segundo piso.

   [LONG_LINE]

**2.** Los estudiantes [suben | subís] al autobús escolar.

   [LONG_LINE]

**3.** Tú [abre | abres] los libros en clase.

   [LONG_LINE]

**4.** La escritora [escribo | escribe] novelas para niños.

   [LONG_LINE]

**5.** Nosotros [vivimos | viven] cerca del parque.

   [LONG_LINE]

**6.** Las niñas [abren | abrís] sus mochilas.

   [LONG_LINE]

**7.** Vosotros [vivís | viven] en el centro de la ciudad.

   [LONG_LINE]

**8.** El escritor [escribo | escribe] libros de aventuras.

   [LONG_LINE]`,
        transformation: `# 指示に従って動詞の人称を変えてください:

**1.** Yo vivo → Nosotros [SHORT_LINE]

**2.** Tú subes → Él [SHORT_LINE]

**3.** Ella abre → Ellas [SHORT_LINE]

**4.** Nosotros escribimos → Yo [SHORT_LINE]

**5.** Vosotros vivís → Tú [SHORT_LINE]

**6.** Él sube → Nosotros [SHORT_LINE]

**7.** Ellas abren → Ella [SHORT_LINE]

**8.** Yo escribo → Vosotros [SHORT_LINE]

## 質問に答えてください:

**1.** ¿Tú escribes emails? → Sí, yo [SHORT_LINE] emails.

**2.** ¿Ellos viven aquí? → Sí, ellos [SHORT_LINE] aquí.

**3.** ¿Vosotros subís al segundo piso? → Sí, nosotros [SHORT_LINE] al segundo piso.

**4.** ¿Ella abre la ventana? → Sí, ella [SHORT_LINE] la ventana.

**5.** ¿Ustedes escriben cartas? → Sí, nosotros [SHORT_LINE] cartas.`,
        ordering: `# 単語を並べ替えて正しい文を作ってください:

**1.** [en / Mi / familia / Madrid / vive]

   私の家族はマドリードに住んでいます。

   [LONG_TALL_LINE]

**2.** [las / abren / Los / niños / cajas]

   子供たちは箱を開けます。

   [LONG_TALL_LINE]

**3.** [cartas / escribe / El / abuelo]

   おじいさんは手紙を書きます。

   [LONG_TALL_LINE]

**4.** [escaleras / subimos / las / Nosotros / despacio]

   私たちはゆっくりと階段を上がります。

   [LONG_TALL_LINE]

**5.** [la / Tú / puerta / abres]

   君はドアを開けます。

   [LONG_TALL_LINE]

**6.** [apartamento / Ella / un / vive / pequeño / en]

   彼女は小さなアパートに住んでいます。

   [LONG_TALL_LINE]`,
        evaluation: `# 文を読んで、正しければB、間違っていればMを書き、間違いを訂正してください:

**1.** Yo vives en una casa azul. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**2.** Los pájaros suben a los árboles. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**3.** Tú abres la puerta con cuidado. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**4.** Nosotros escriben cartas a Santa Claus. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**5.** Mi gato vive en el jardín. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**6.** Vosotros subís la montaña en verano. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**7.** Ellas vive en apartamentos modernos. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**8.** Tú abrir la puerta con la llave. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]`,
      },
      'english': {
        dialogue: `# Dialogue

## In the garden (En el jardín)

**Laura:** ¡Qué bonitas flores! ¿Tú las cuidas?

**Diego:** Sí, yo **vivo** aquí con mis abuelos. Ellos tienen un jardín grande.

**Laura:** ¿**Vives** aquí todo el año?

**Diego:** Sí, **vivo** aquí desde el año pasado. Me gusta mucho.

**Laura:** Mis abuelos también **viven** en una casa con jardín.

**Diego:** ¿Ellos cuidan plantas también?

**Laura:** No, pero mi abuela **escribe** sobre jardines en su blog.

**Diego:** ¡Qué interesante! ¿Tú también **escribes**?

**Laura:** Un poco. **Escribo** en mi diario todas las noches.
`,
        conjugation: `# Present tense - Verb VIVIR (to live)

| yo            | vivo  | nosotros/nosotras   | vivimos |
| ------------- | ----- | ------------------- | ------- |
| tú            | vives | vosotros/vosotras   | vivís   |
| él/ella/usted | vive  | ellos/ellas/ustedes | viven   |

**Example (Ejemplo):** Yo vivo en una casa cerca de la escuela.

## Complete the sentences with the correct verb form:

**1.** Yo [SHORT_LINE] (escribir) postales a mis amigos.

**2.** Tú [SHORT_LINE] (abrir) la ventana cuando hace calor.

**3.** Ella [SHORT_LINE] (vivir) en el centro de la ciudad.

**4.** Nosotros [SHORT_LINE] (subir) las escaleras todos los días.

**5.** Ellos [SHORT_LINE] (escribir) sus nombres en la lista.

**6.** Vosotros [SHORT_LINE] (vivir) cerca de la playa.

**7.** Usted [SHORT_LINE] (abrir) la tienda por la mañana.

**8.** Mis primos [SHORT_LINE] (subir) la montaña en verano.

**9.** Tú [SHORT_LINE] (escribir) muy bien las cartas.

**10.** Nosotras [SHORT_LINE] (vivir) en el mismo barrio.
`,
        choice: `# Choose the correct form and write the complete sentence:

**1.** Mi hermano [vive | vives] en el segundo piso.

   [LONG_LINE]

**2.** Los estudiantes [suben | subís] al autobús escolar.

   [LONG_LINE]

**3.** Tú [abre | abres] los libros en clase.

   [LONG_LINE]

**4.** La escritora [escribo | escribe] novelas para niños.

   [LONG_LINE]

**5.** Nosotros [vivimos | viven] cerca del parque.

   [LONG_LINE]

**6.** Las niñas [abren | abrís] sus mochilas.

   [LONG_LINE]

**7.** Vosotros [vivís | viven] en el centro de la ciudad.

   [LONG_LINE]

**8.** El escritor [escribo | escribe] libros de aventuras.

   [LONG_LINE]`,
        transformation: `# Change the person of the verb as indicated:

**1.** Yo vivo → Nosotros [SHORT_LINE]

**2.** Tú subes → Él [SHORT_LINE]

**3.** Ella abre → Ellas [SHORT_LINE]

**4.** Nosotros escribimos → Yo [SHORT_LINE]

**5.** Vosotros vivís → Tú [SHORT_LINE]

**6.** Él sube → Nosotros [SHORT_LINE]

**7.** Ellas escriben → Ella [SHORT_LINE]

**8.** Yo abro → Vosotros [SHORT_LINE]

## Answer the questions:

**1.** ¿Tú escribes emails? → Sí, yo [SHORT_LINE] emails.

**2.** ¿Ellos viven aquí? → Sí, ellos [SHORT_LINE] aquí.

**3.** ¿Vosotros subís montañas? → Sí, nosotros [SHORT_LINE] montañas.

**4.** ¿Ella abre ventanas? → Sí, ella [SHORT_LINE] ventanas.

**5.** ¿Ustedes escriben cartas? → Sí, nosotros [SHORT_LINE] cartas.`,
        ordering: `# Put the words in the correct order to form sentences:

**1.** [en / Mi / familia / Madrid / vive]

   My family lives in Madrid

   [LONG_TALL_LINE]

**2.** [las / abren / Los / niños / cajas]

   The children open the boxes

   [LONG_TALL_LINE]

**3.** [cartas / escribe / El / abuelo]

   Grandfather writes letters

   [LONG_TALL_LINE]

**4.** [escaleras / subimos / las / Nosotros / despacio]

   We go up the stairs slowly

   [LONG_TALL_LINE]

**5.** [la / Tú / puerta / abres]

   You open the door

   [LONG_TALL_LINE]

**6.** [apartamento / Ella / un / vive / pequeño / en]

   She lives in a small apartment

   [LONG_TALL_LINE]`,
        evaluation: `# Read the sentences. If correct, write R. If incorrect, write W and correct:

**1.** Yo vives en una casa azul. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**2.** Los pájaros suben a los árboles. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**3.** Tú abres la puerta con cuidado. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**4.** Nosotros escriben cartas a Santa Claus. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**5.** Mi gato vive en el jardín. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**6.** Vosotros subís la montaña en verano. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**7.** Ellas abren las ventanas. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**8.** Tú escribes emails importantes. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]`,
      },
    },
    '4': {
      'japanese': {
        dialogue: `# 会話

## 学校で (En la escuela)

**Ana:** ¡Hola Carlos! ¿Qué **haces** aquí?

**Carlos:** **Busco** mi libro de matemáticas. ¿Tú **comes** aquí en el recreo*?

**Ana:** Sí, siempre **como** mi bocadillo aquí. ¿**Vives** cerca de la escuela?

**Carlos:** No, **vivo** lejos. Mi hermana y yo **aprendemos** español los martes.

**Ana:** ¡Qué bien! Yo **escribo** cartas a mi abuela de España.

**Carlos:** Mi familia **habla** español en casa. ¿Tú **lees** libros en español?

**Ana:** Sí, **leo** cuentos cortos. Mi madre **bebe** café mientras yo **leo**.

**Carlos:** Nosotros **bailamos** salsa los fines de semana. ¿Tú **dibujas**?

**Ana:** **Dibujo** animales. Mi hermano **abre** su cuaderno y **dibuja** conmigo.

**Carlos:** ¡Genial! Nosotros **subimos** las escaleras todos los días.

*recreo = 休み時間`,
        conjugation: `# 動詞の原形を見つけましょう

活用された動詞を見て、その原形を書いてください。

**例:** Ella **habla** con su mamá → 原形: **hablar**

**1.** Los niños **comen** fruta en el recreo → [SHORT_LINE]

**2.** María **dibuja** flores en su cuaderno → [SHORT_LINE]

**3.** Nosotros **vivimos** en una casa grande → [SHORT_LINE]

**4.** Tú **buscas** tu pelota en el jardín → [SHORT_LINE]

**5.** Ellos **abren** las ventanas por la mañana → [SHORT_LINE]

## 正しい形で空欄を埋めてください:

**1.** Yo [SHORT_LINE] (hablar) español con mis abuelos.

**2.** Tú [SHORT_LINE] (comer) fruta en el desayuno.

**3.** Ella [SHORT_LINE] (vivir) cerca de la estación.

**4.** Nosotros [SHORT_LINE] (leer) libros interesantes.

**5.** Ellos [SHORT_LINE] (bailar) en la fiesta de cumpleaños.

**6.** Vosotros [SHORT_LINE] (escribir) cartas a vuestros amigos.

**7.** Usted [SHORT_LINE] (beber) té todas las mañanas.

**8.** Mis hermanas [SHORT_LINE] (aprender) a tocar el piano.

**9.** Tú [SHORT_LINE] (subir) las escaleras muy rápido.

**10.** Nosotras [SHORT_LINE] (abrir) las ventanas de la clase.`,
        choice: `# 正しい形を選んで完全な文を書いてください:

**1.** Los estudiantes [aprenden | aprende] inglés en la escuela.

   [LONG_LINE]

**2.** Mi hermana [baila | bailan] muy bien en las fiestas.

   [LONG_LINE]

**3.** Nosotros [lee | leemos] libros interesantes en la biblioteca.

   [LONG_LINE]

**4.** Tú [escribes | escriben] cartas a tus amigos.

   [LONG_LINE]

**5.** El gato [sube | suben] al árbol del jardín.

   [LONG_LINE]

**6.** Las niñas [bebe | beben] agua después de correr.

   [LONG_LINE]

**7.** Mis padres [viven | vive] cerca del parque.

   [LONG_LINE]

**8.** Vosotros [comemos | coméis] fruta en el recreo.

   [LONG_LINE]`,
        transformation: `# 指示に従って動詞の人称を変えてください:

**1.** Yo hablo → Nosotros [SHORT_LINE]

**2.** Tú comes → Él [SHORT_LINE]

**3.** Ella vive → Ellas [SHORT_LINE]

**4.** Nosotros buscamos → Yo [SHORT_LINE]

**5.** Vosotros leéis → Tú [SHORT_LINE]

**6.** Él aprende → Nosotros [SHORT_LINE]

**7.** Ellas escriben → Ella [SHORT_LINE]

**8.** Yo bebo → Vosotros [SHORT_LINE]

## 質問に答えてください:

**1.** ¿Tú dibujas animales? → Sí, yo [SHORT_LINE] animales.

**2.** ¿Ellos abren la puerta? → No, ellos no [SHORT_LINE] la puerta.

**3.** ¿Vosotros bailáis salsa? → Sí, nosotros [SHORT_LINE] salsa.

**4.** ¿Ella sube escaleras? → Sí, ella [SHORT_LINE] escaleras.

**5.** ¿Ustedes viven cerca? → Sí, nosotros [SHORT_LINE] cerca.`,
        ordering: `# 正しい順番に並べましょう

**1.** [aprende / Mi / hermano / japonés / en / la / escuela]

私の兄弟は学校で日本語を学びます。

[LONG_LINE]

**2.** [leemos / Nosotros / cuentos / interesantes / casa / en]

私たちは家で面白い絵本を読みます。

[LONG_LINE]

**3.** [bailan / Los / niños / en / el / patio / felices]

子供たちは中庭で楽しく踊ります。

[LONG_LINE]

**4.** [escribo / cartas / a / mis / abuelos / Yo]

私は祖父母に手紙を書きます。

[LONG_LINE]

**5.** [sube / gato / El / árbol / al / rápido]

猫は素早く木に登ります。

[LONG_LINE]

**6.** [beben / agua / después / Los / deportistas / de / correr]

スポーツ選手は走った後に水を飲みます。

[LONG_LINE]`,
        evaluation: `# 文を読んで、正しければB、間違っていればMを書き、間違いを訂正してください:

**1.** Los estudiantes aprende matemáticas en la escuela. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**2.** Mi hermana dibuja flores muy bonitas. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**3.** Nosotros viven en una casa grande. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**4.** Tú bebes leche todas las mañanas. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**5.** El perro abren la puerta con la pata. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**6.** Mis padres hablan español y japonés. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**7.** Ella escriben cartas a su abuela. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**8.** Tú leer libros de aventuras. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]`,
      },
      'english': {
        dialogue: `# Dialogue

## At school (En la escuela)

**Ana:** ¡Hola Carlos! ¿Qué **haces** aquí?

**Carlos:** **Busco** mi libro de matemáticas. ¿Tú **comes** aquí en el recreo*?

**Ana:** Sí, siempre **como** mi bocadillo aquí. ¿**Vives** cerca de la escuela?

**Carlos:** No, **vivo** lejos. Mi hermana y yo **aprendemos** español los martes.

**Ana:** ¡Qué bien! Yo **escribo** cartas a mi abuela de España.

**Carlos:** Mi familia **habla** español en casa. ¿Tú **lees** libros en español?

**Ana:** Sí, **leo** cuentos cortos. Mi madre **bebe** café mientras yo **leo**.

**Carlos:** Nosotros **bailamos** salsa los fines de semana. ¿Tú **dibujas**?

**Ana:** **Dibujo** animales. Mi hermano **abre** su cuaderno y **dibuja** conmigo.

**Carlos:** ¡Genial! Nosotros **subimos** las escaleras todos los días.

*recreo = break time`,
        conjugation: `# Find the base form of the verb

Look at the conjugated verb and write its base form.

**Example:** Ella **habla** con su mamá → Base form: **hablar**

**1.** Los niños **comen** fruta en el recreo → [SHORT_LINE]

**2.** María **dibuja** flores en su cuaderno → [SHORT_LINE]

**3.** Nosotros **vivimos** en una casa grande → [SHORT_LINE]

**4.** Tú **buscas** tu pelota en el jardín → [SHORT_LINE]

**5.** Ellos **abren** las ventanas por la mañana → [SHORT_LINE]

## Fill in the blanks with the correct form:

**1.** Yo [SHORT_LINE] (hablar) español con mis abuelos.

**2.** Tú [SHORT_LINE] (comer) fruta en el desayuno.

**3.** Ella [SHORT_LINE] (vivir) cerca de la estación.

**4.** Nosotros [SHORT_LINE] (leer) libros interesantes.

**5.** Ellos [SHORT_LINE] (bailar) en la fiesta de cumpleaños.

**6.** Vosotros [SHORT_LINE] (escribir) cartas a vuestros amigos.

**7.** Usted [SHORT_LINE] (beber) té todas las mañanas.

**8.** Mis hermanas [SHORT_LINE] (aprender) a tocar el piano.

**9.** Tú [SHORT_LINE] (subir) las escaleras muy rápido.

**10.** Nosotras [SHORT_LINE] (abrir) las ventanas de la clase.`,
        choice: `# Choose the correct form and write the complete sentence:

**1.** Los estudiantes [aprenden | aprende] inglés en la escuela.

   [LONG_LINE]

**2.** Mi hermana [baila | bailan] muy bien en las fiestas.

   [LONG_LINE]

**3.** Nosotros [lee | leemos] libros interesantes en la biblioteca.

   [LONG_LINE]

**4.** Tú [escribes | escriben] cartas a tus amigos.

   [LONG_LINE]

**5.** El gato [sube | suben] al árbol del jardín.

   [LONG_LINE]

**6.** Las niñas [bebe | beben] agua después de correr.

   [LONG_LINE]

**7.** Mis padres [viven | vive] cerca del parque.

   [LONG_LINE]

**8.** Vosotros [comemos | coméis] fruta en el recreo.

   [LONG_LINE]`,
        transformation: `# Follow the instructions and change the person of the verb:

**1.** Yo hablo → Nosotros [SHORT_LINE]

**2.** Tú comes → Él [SHORT_LINE]

**3.** Ella vive → Ellas [SHORT_LINE]

**4.** Nosotros buscamos → Yo [SHORT_LINE]

**5.** Vosotros leéis → Tú [SHORT_LINE]

**6.** Él aprende → Nosotros [SHORT_LINE]

**7.** Ellas escriben → Ella [SHORT_LINE]

**8.** Yo bebo → Vosotros [SHORT_LINE]

## Answer the questions:

**1.** ¿Tú dibujas animales? → Sí, yo [SHORT_LINE] animales.

**2.** ¿Ellos abren la puerta? → No, ellos no [SHORT_LINE] la puerta.

**3.** ¿Vosotros bailáis salsa? → Sí, nosotros [SHORT_LINE] salsa.

**4.** ¿Ella sube escaleras? → Sí, ella [SHORT_LINE] escaleras.

**5.** ¿Ustedes viven cerca? → Sí, nosotros [SHORT_LINE] cerca.`,
        ordering: `# Put the words in the correct order

**1.** [aprende / Mi / hermano / japonés / en / la / escuela]

My brother learns Japanese at school.

[LONG_LINE]

**2.** [leemos / Nosotros / cuentos / interesantes / casa / en]

We read interesting stories at home.

[LONG_LINE]

**3.** [bailan / Los / niños / en / el / patio / felices]

The children dance happily in the courtyard.

[LONG_LINE]

**4.** [escribo / cartas / a / mis / abuelos / Yo]

I write letters to my grandparents.

[LONG_LINE]

**5.** [sube / gato / El / árbol / al / rápido]

The cat climbs the tree quickly.

[LONG_LINE]

**6.** [beben / agua / después / Los / deportistas / de / correr]

The athletes drink water after running.

[LONG_LINE]`,
        evaluation: `# Read the sentence and write B if correct, M if incorrect, and correct the mistakes:

**1.** Los estudiantes aprende matemáticas en la escuela. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**2.** Mi hermana dibuja flores muy bonitas. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**3.** Nosotros viven en una casa grande. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**4.** Tú bebes leche todas las mañanas. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**5.** El perro abren la puerta con la pata. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**6.** Mis padres hablan español y japonés. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**7.** Ella escriben cartas a su abuela. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**8.** Tú leer libros de aventuras. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]`,
      },
    },
  },
  'past-tense': {
    '1': {
      'japanese': {
        dialogue: `# 会話

## 昨日のことについて (Sobre lo que pasó ayer)

**María:** ¡Hola, Luis! ¿Qué hiciste ayer?

**Luis:** Hola, María. Yo **dibujé** un perro en mi cuaderno. ¿Te **gustó**?

**María:** ¡Sí! **Dibujaste** muy bien. Yo **busqué** mi libro de historia toda la tarde.

**Luis:** ¿**Encontraste** el libro?

**María:** Sí, lo **encontré** al final. Después mis padres **hablaron** conmigo sobre mis notas del examen.

**Luis:** Mis padres también **hablaron** conmigo ayer sobre la escuela.

**María:** ¿Qué hiciste después de estudiar?

**Luis:** **Dibujé** más animales. ¿Y tú qué hiciste?

**María:** Yo **bailé** con mi hermana. Nos **gustó** mucho bailar juntas.`,
        conjugation: `# 過去形 - 動詞 HABLAR (話した)

| yo            | hablé    | nosotros/nosotras   | hablamos   |
| ------------- | -------- | ------------------- | ---------- |
| tú            | hablaste | vosotros/vosotras   | hablasteis |
| él/ella/usted | habló    | ellos/ellas/ustedes | hablaron   |

**例文:** Yo hablé español ayer con mi abuela.

## 正しい形で空欄を過去形で埋めてください:

**1.** Yo [SHORT_LINE] (dibujar) un gato en mi cuaderno ayer.

**2.** Tú [SHORT_LINE] (buscar) tu mochila en la clase por la mañana.

**3.** Ella [SHORT_LINE] (bailar) muy bien en la fiesta del sábado.

**4.** Nosotros [SHORT_LINE] (hablar) japonés en la escuela el lunes.

**5.** Ellos [SHORT_LINE] (dibujar) flores en el jardín la semana pasada.

**6.** Vosotros [SHORT_LINE] (bailar) flamenco el viernes pasado.

**7.** Usted [SHORT_LINE] (buscar) trabajo en la ciudad el mes pasado.

**8.** Mis hermanos [SHORT_LINE] (hablar) con sus amigos ayer por la tarde.

**9.** Tú [SHORT_LINE] (dibujar) muy bien los animales el domingo.

**10.** Nosotras [SHORT_LINE] (buscar) un regalo para mamá la semana pasada.
`,
        choice: `# 正しい動詞の形を選んでください:

**1.** Ana [dibujó | dibujaron] una casa bonita ayer.

[LONG_LINE]

**2.** Los niños [buscaste | buscaron] sus juguetes en el parque.

[LONG_LINE]

**3.** Tú [bailó | bailaste] muy bien en la fiesta anoche.

[LONG_LINE]

**4.** Mi familia [habló | hablamos] sobre las vacaciones.

[LONG_LINE]

**5.** Pedro [dibujé | dibujó] un árbol grande en su papel.

[LONG_LINE]

**6.** Vosotros [buscaron | buscasteis] el gato toda la tarde.

[LONG_LINE]

**7.** Las chicas [bailaron | bailaste] salsa en la escuela ayer.

[LONG_LINE]

**8.** Yo [hablé | habló] con mi profesora sobre mi tarea.

[LONG_LINE]`,
        transformation: `# 指示に従って動詞の人称を変えてください:

**1.** Yo dibujé → Nosotros [SHORT_LINE]

**2.** Tú hablaste → Él [SHORT_LINE]

**3.** Ella bailó → Ellas [SHORT_LINE]

**4.** Nosotros buscamos → Yo [SHORT_LINE]

**5.** Vosotros bailasteis → Tú [SHORT_LINE]

**6.** Él habló → Nosotros [SHORT_LINE]

**7.** Ellas dibujaron → Ella [SHORT_LINE]

**8.** Yo busqué → Vosotros [SHORT_LINE]

## 質問に答えてください:

**1.** ¿Tú dibujaste animales? → Sí, yo [SHORT_LINE] animales.

**2.** ¿Ellos buscaron trabajo? → Sí, ellos [SHORT_LINE] trabajo.

**3.** ¿Vosotros bailasteis salsa? → Sí, nosotros [SHORT_LINE] salsa.

**4.** ¿Ella habló japonés? → Sí, ella [SHORT_LINE] japonés.

**5.** ¿Ustedes dibujaron bien? → Sí, nosotros [SHORT_LINE] bien.`,
        ordering: `# 正しい順序に並べ替えてください:

**1.** [ayer / dibujé / un / perro / Yo]
昨日私は犬を描いた。

[LONG_TALL_LINE]

**2.** [buscaron / en / sus / llaves / Ellos / la / cocina]
彼らは台所で鍵を探した。

[LONG_TALL_LINE]

**3.** [bailaste / muy / en / bien / la / Tú / fiesta]
あなたはパーティーでとても上手に踊った。

[LONG_TALL_LINE]

**4.** [con / hablamos / nuestros / Nosotros / padres]
私たちは両親と話した。

[LONG_TALL_LINE]

**5.** [dibujó / Ana / flores / bonitas / muchas]
アナはたくさんの美しい花を描いた。

[LONG_TALL_LINE]

**6.** [el / buscó / toda / gato / tarde / la / Pedro]
ペドロは午後中ずっと猫を探した。

[LONG_TALL_LINE]`,
        evaluation: `# 文が正しいか間違っているか判断してください (B = bien 正しい / M = mal 間違い):

**1.** Yo dibujé una casa ayer. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**2.** Tú buscaron tus llaves en la mesa. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**3.** Ella bailó muy bien en la fiesta. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**4.** Nosotros hablaste con el profesor. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**5.** Ellos dibujaron flores bonitas. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**6.** Vosotros buscó el libro perdido. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**7.** María habló con su amiga por teléfono. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**8.** Yo bailaron toda la noche. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]`,
      },
      'english': {
        dialogue: `# Dialogue

## About what happened yesterday (Sobre lo que pasó ayer)

**María:** ¡Hola, Luis! ¿Qué hiciste ayer?

**Luis:** Hola, María. Yo **dibujé** un perro en mi cuaderno. ¿Te **gustó**?

**María:** ¡Sí! **Dibujaste** muy bien. Yo **busqué** mi libro de historia toda la tarde.

**Luis:** ¿**Encontraste** el libro?

**María:** Sí, lo **encontré** al final. Después mis padres **hablaron** conmigo sobre mis notas del examen.

**Luis:** Mis padres también **hablaron** conmigo ayer sobre la escuela.

**María:** ¿Qué hiciste después de estudiar?

**Luis:** **Dibujé** más animales. ¿Y tú qué hiciste?

**María:** Yo **bailé** con mi hermana. Nos **gustó** mucho bailar juntas.`,
        conjugation: `# Past tense - Verb HABLAR (to speak)

| yo            | hablé  | nosotros/nosotras   | hablamos |
| ------------- | ------ | ------------------- | -------- |
| tú            | hablaste | vosotros/vosotras   | hablasteis  |
| él/ella/usted | habló  | ellos/ellas/ustedes | hablaron   |

**Example:** Yo hablé español ayer con mi abuela.

## Fill in the blanks with the correct past tense form:

**1.** Yo [SHORT_LINE] (dibujar) un gato en mi cuaderno ayer.

**2.** Tú [SHORT_LINE] (buscar) tu mochila en la clase por la mañana.

**3.** Ella [SHORT_LINE] (bailar) muy bien en la fiesta del sábado.

**4.** Nosotros [SHORT_LINE] (hablar) japonés en la escuela el lunes.

**5.** Ellos [SHORT_LINE] (dibujar) flores en el jardín la semana pasada.

**6.** Vosotros [SHORT_LINE] (bailar) flamenco el viernes pasado.

**7.** Usted [SHORT_LINE] (buscar) trabajo en la ciudad el mes pasado.

**8.** Mis hermanos [SHORT_LINE] (hablar) con sus amigos ayer por la tarde.

**9.** Tú [SHORT_LINE] (dibujar) muy bien los animales el domingo.

**10.** Nosotras [SHORT_LINE] (buscar) un regalo para mamá la semana pasada.`,
        choice: `# Choose the correct verb form:

**1.** Ana [dibujó | dibujaron] una casa bonita ayer.

[LONG_LINE]

**2.** Los niños [buscaste | buscaron] sus juguetes en el parque.

[LONG_LINE]

**3.** Tú [bailó | bailaste] muy bien en la fiesta anoche.

[LONG_LINE]

**4.** Mi familia [habló | hablamos] sobre las vacaciones.

[LONG_LINE]

**5.** Pedro [dibujé | dibujó] un árbol grande en su papel.

[LONG_LINE]

**6.** Vosotros [buscaron | buscasteis] el gato toda la tarde.

[LONG_LINE]

**7.** Las chicas [bailaron | bailaste] salsa en la escuela ayer.

[LONG_LINE]

**8.** Yo [hablé | habló] con mi profesora sobre mi tarea.

[LONG_LINE]`,
        transformation: `# Change the person of the verb as indicated:

**1.** Yo dibujé → Nosotros [SHORT_LINE]

**2.** Tú hablaste → Él [SHORT_LINE]

**3.** Ella bailó → Ellas [SHORT_LINE]

**4.** Nosotros buscamos → Yo [SHORT_LINE]

**5.** Vosotros bailasteis → Tú [SHORT_LINE]

**6.** Él habló → Nosotros [SHORT_LINE]

**7.** Ellas dibujaron → Ella [SHORT_LINE]

**8.** Yo busqué → Vosotros [SHORT_LINE]

## Answer the questions:

**1.** ¿Tú dibujaste animales? → Sí, yo [SHORT_LINE] animales.

**2.** ¿Ellos buscaron trabajo? → Sí, ellos [SHORT_LINE] trabajo.

**3.** ¿Vosotros bailasteis salsa? → Sí, nosotros [SHORT_LINE] salsa.

**4.** ¿Ella habló japonés? → Sí, ella [SHORT_LINE] japonés.

**5.** ¿Ustedes dibujaron bien? → Sí, nosotros [SHORT_LINE] bien.`,
        ordering: `# Put the words in the correct order:

**1.** [ayer / dibujé / un / perro / Yo]
Yesterday I drew a dog.

[LONG_TALL_LINE]

**2.** [buscaron / en / sus / llaves / Ellos / la / cocina]
They looked for their keys in the kitchen.

[LONG_TALL_LINE]

**3.** [bailaste / muy / en / bien / la / Tú / fiesta]
You danced very well at the party.

[LONG_TALL_LINE]

**4.** [con / hablamos / nuestros / Nosotros / padres]
We talked with our parents.

[LONG_TALL_LINE]

**5.** [dibujó / Ana / flores / bonitas / muchas]
Ana drew many beautiful flowers.

[LONG_TALL_LINE]

**6.** [el / buscó / toda / gato / tarde / la / Pedro]
Pedro looked for the cat all afternoon.

[LONG_TALL_LINE]`,
        evaluation: `# Decide if the sentences are correct or incorrect (B = bien/right / M = mal/wrong):

**1.** Yo dibujé una casa ayer. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**2.** Tú buscaron tus llaves en la mesa. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**3.** Ella bailó muy bien en la fiesta. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**4.** Nosotros hablaste con el profesor. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**5.** Ellos dibujaron flores bonitas. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**6.** Vosotros buscó el libro perdido. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**7.** María habló con su amiga por teléfono. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**8.** Yo bailaron toda la noche. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]`,
      },
    },
    '2': {
      'japanese': {
        dialogue: `# 会話

## 休憩時間にしたこと (Lo que hicimos en el descanso)

**Ana:** ¡Hola, Pedro! ¿Qué hiciste en el descanso?

**Pedro:** Hola, Ana. Yo **leí** un libro muy interesante en la biblioteca. ¿Te gustó el que te recomendé?

**Ana:** ¡Sí! **Leíste** una historia muy bonita. Yo **comí** mi almuerzo con mis amigas en el patio.

**Pedro:** ¿**Comiste** toda la comida?

**Ana:** Sí, la **comí** toda. También **bebí** agua después de jugar. ¿Tú qué más hiciste?

**Pedro:** Yo **aprendí** palabras nuevas en inglés con la profesora.

**Ana:** ¿**Aprendiste** muchas palabras?

**Pedro:** Sí, **aprendí** cinco palabras nuevas. Después **bebí** leche en el recreo.

**Ana:** Mis compañeros también **aprendieron** mucho en la clase de español ayer.`,
        conjugation: `# 過去形 - 動詞 COMER (食べる)

| yo            | comí  | nosotros/nosotras   | comimos |
| ------------- | ----- | ------------------- | ------- |
| tú            | comiste | vosotros/vosotras   | comisteis  |
| él/ella/usted | comió  | ellos/ellas/ustedes | comieron   |

**例文:** Yo comí fruta fresca en el almuerzo ayer.

## 正しい形で空欄を過去形で埋めてください:

**1.** Yo [SHORT_LINE] (leer) una revista interesante anoche.

**2.** Tú [SHORT_LINE] (aprender) francés el año pasado.

**3.** Ella [SHORT_LINE] (beber) zumo de naranja en el desayuno.

**4.** Nosotros [SHORT_LINE] (comer) pizza en la fiesta del sábado.

**5.** Ella [SHORT_LINE] (beber) agua después del ejercicio.

**6.** Vosotros [SHORT_LINE] (aprender) a cocinar el mes pasado.

**7.** Usted [SHORT_LINE] (beber) té caliente por la tarde.

**8.** Mis hermanas [SHORT_LINE] (comer) helado después de la cena.

**9.** Tú [SHORT_LINE] (leer) muchos libros durante las vacaciones.

**10.** Nosotras [SHORT_LINE] (aprender) canciones nuevas en la clase de música.`,
        choice: `# 正しい選択肢を選んで完全な文を書いてください:

**1.** Ana [comió | comieron] chocolate después de la cena.

[LONG_LINE]

**2.** Los niños [leyó | leyeron] cuentos en la biblioteca ayer.

[LONG_LINE]

**3.** María [aprendió | aprendieron] a tocar la guitarra el verano pasado.

[LONG_LINE]

**4.** Nosotros [bebimos | bebió] agua fría después del partido.

[LONG_LINE]

**5.** Miguel [comiste | comió] ensalada en el almuerzo.

[LONG_LINE]

**6.** Vosotros [leísteis | leyeron] el periódico esta mañana.

[LONG_LINE]

**7.** La profesora [aprendió | aprendieron] alemán cuando era joven.

[LONG_LINE]

**8.** Tú [bebiste | bebió] leche antes de acostarte anoche.

[LONG_LINE]`,
        transformation: `# 指示に従って動詞の人称を変えてください:

**1.** Yo comí → Nosotros [SHORT_LINE]

**2.** Tú leíste → Él [SHORT_LINE]

**3.** Ella aprendió → Ellas [SHORT_LINE]

**4.** Nosotros bebimos → Yo [SHORT_LINE]

**5.** Vosotros comisteis → Tú [SHORT_LINE]

**6.** Él aprendió → Nosotros [SHORT_LINE]

**7.** Ellas leyeron → Ella [SHORT_LINE]

**8.** Yo bebí → Vosotros [SHORT_LINE]

## 質問に答えてください:

**1.** ¿Tú leíste novelas? → Sí, yo [SHORT_LINE] novelas.

**2.** ¿Ellos comieron pescado? → Sí, ellos [SHORT_LINE] pescado.

**3.** ¿Vosotros bebisteis café? → Sí, nosotros [SHORT_LINE] café.

**4.** ¿Ella aprendió inglés? → Sí, ella [SHORT_LINE] inglés.

**5.** ¿Ustedes comieron verduras? → Sí, nosotros [SHORT_LINE] verduras.`,
        ordering: `# 単語を正しい順番に並べて文を完成させてください:

**1.** [ayer / comió / Ana / verduras / frescas]
昨日アナは新鮮な野菜を食べました

[LONG_TALL_LINE]

**2.** [libro / leímos / interesante / Nosotros / un]
私たちは面白い本を読みました

[LONG_TALL_LINE]

**3.** [Mis / aprendieron / padres / italiano / el / año / pasado]
私の両親は去年イタリア語を学びました

[LONG_TALL_LINE]

**4.** [café / bebiste / caliente / Tú / esta / mañana]
あなたは今朝温かいコーヒーを飲みました

[LONG_TALL_LINE]

**5.** [en / comieron / Los / niños / el / recreo / bocadillos]
子供たちは休み時間にサンドイッチを食べました

[LONG_TALL_LINE]

**6.** [libro / un / leyó / difícil / El / estudiante]
学生は難しい本を読みました

[LONG_TALL_LINE]`,
        evaluation: `# 文が正しければB（bien）、間違っていればM（mal）を書いてください:

**1.** Mi hermana comió pasta ayer. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**2.** Nosotros leí libros en la biblioteca. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**3.** Nosotros aprendimos inglés el año pasado. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**4.** Tú bebiste agua después del ejercicio. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**5.** María y Ana comieron pizza en la cena. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**6.** Yo leí una carta de mi abuela ayer. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**7.** Vosotros aprendió matemáticas rápidamente. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**8.** El niño bebió leche antes de dormir. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]`,
      },
      'english': {
        dialogue: `# Dialogue

## What we did during break time

**Ana:** ¡Hola, Pedro! ¿Qué hiciste en el descanso?

**Pedro:** Hola, Ana. Yo **leí** un libro muy interesante en la biblioteca. ¿Te gustó el que te recomendé?

**Ana:** ¡Sí! **Leíste** una historia muy bonita. Yo **comí** mi almuerzo con mis amigas en el patio.

**Pedro:** ¿**Comiste** toda la comida?

**Ana:** Sí, la **comí** toda. También **bebí** agua después de jugar. ¿Tú qué más hiciste?

**Pedro:** Yo **aprendí** palabras nuevas en inglés con la profesora.

**Ana:** ¿**Aprendiste** muchas palabras?

**Pedro:** Sí, **aprendí** cinco palabras nuevas. Después **bebí** leche en el recreo.

**Ana:** Mis compañeros también **aprendieron** mucho en la clase de español ayer.`,
        conjugation: `# Past tense - Verb COMER (to eat)

| yo            | comí  | nosotros/nosotras   | comimos |
| ------------- | ----- | ------------------- | ------- |
| tú            | comiste | vosotros/vosotras   | comisteis  |
| él/ella/usted | comió  | ellos/ellas/ustedes | comieron   |

**Example:** Yo comí fruta fresca en el almuerzo ayer.

## Fill in the blanks with the correct past tense form:

**1.** Yo [SHORT_LINE] (leer) una revista interesante anoche.

**2.** Tú [SHORT_LINE] (aprender) francés el año pasado.

**3.** Ella [SHORT_LINE] (beber) zumo de naranja en el desayuno.

**4.** Nosotros [SHORT_LINE] (comer) pizza en la fiesta del sábado.

**5.** Ella [SHORT_LINE] (beber) agua después del ejercicio.

**6.** Vosotros [SHORT_LINE] (aprender) a cocinar el mes pasado.

**7.** Usted [SHORT_LINE] (beber) té caliente por la tarde.

**8.** Mis hermanas [SHORT_LINE] (comer) helado después de la cena.

**9.** Tú [SHORT_LINE] (leer) muchos libros durante las vacaciones.

**10.** Nosotras [SHORT_LINE] (aprender) canciones nuevas en la clase de música.`,
        choice: `# Choose the correct option and write the complete sentence:

**1.** Ana [comió | comieron] chocolate después de la cena.

[LONG_LINE]

**2.** Los niños [leyó | leyeron] cuentos en la biblioteca ayer.

[LONG_LINE]

**3.** María [aprendió | aprendieron] a tocar la guitarra el verano pasado.

[LONG_LINE]

**4.** Nosotros [bebimos | bebió] agua fría después del partido.

[LONG_LINE]

**5.** Miguel [comiste | comió] ensalada en el almuerzo.

[LONG_LINE]

**6.** Vosotros [leísteis | leyeron] el periódico esta mañana.

[LONG_LINE]

**7.** La profesora [aprendió | aprendieron] alemán cuando era joven.

[LONG_LINE]

**8.** Tú [bebiste | bebió] leche antes de acostarte anoche.

[LONG_LINE]`,
        transformation: `# Change the person as instructed:

**1.** Yo comí → Nosotros [SHORT_LINE]

**2.** Tú leíste → Él [SHORT_LINE]

**3.** Ella aprendió → Ellas [SHORT_LINE]

**4.** Nosotros bebimos → Yo [SHORT_LINE]

**5.** Vosotros comisteis → Tú [SHORT_LINE]

**6.** Él leyó → Nosotros [SHORT_LINE]

**7.** Ellas aprendieron → Ella [SHORT_LINE]

**8.** Yo bebí → Vosotros [SHORT_LINE]

## Answer the questions:

**1.** ¿Tú comiste pizza? → Sí, yo [SHORT_LINE] pizza.

**2.** ¿Ellos leyeron el libro? → Sí, ellos [SHORT_LINE] el libro.

**3.** ¿Vosotros aprendisteis español? → Sí, nosotros [SHORT_LINE] español.

**4.** ¿Ella bebió agua? → Sí, ella [SHORT_LINE] agua.

**5.** ¿Ustedes comieron temprano? → Sí, nosotros [SHORT_LINE] temprano.`,
        ordering: `# Put the words in the correct order to complete the sentence:

**1.** [ayer / comió / Ana / verduras / frescas]
Yesterday Ana ate fresh vegetables

[LONG_TALL_LINE]

**2.** [libro / leímos / interesante / Nosotros / un]
We read an interesting book

[LONG_TALL_LINE]

**3.** [Mis / aprendieron / padres / italiano / el / año / pasado]
My parents learned Italian last year

[LONG_TALL_LINE]

**4.** [café / bebiste / caliente / Tú / esta / mañana]
You drank hot coffee this morning

[LONG_TALL_LINE]

**5.** [en / comieron / Los / niños / el / recreo / bocadillos]
The children ate sandwiches at recess

[LONG_TALL_LINE]

**6.** [libro / un / leyó / difícil / El / estudiante]
The student read a difficult book

[LONG_TALL_LINE]`,
        evaluation: `# Write B (bien) if the sentence is correct, M (mal) if it's wrong:

**1.** Mi hermana comió pasta ayer. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**2.** Nosotros leí libros en la biblioteca. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**3.** Nosotros aprendimos inglés el año pasado. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**4.** Tú bebiste agua después del ejercicio. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**5.** María y Ana comieron pizza en la cena. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**6.** Yo leí una carta de mi abuela ayer. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**7.** Vosotros aprendió matemáticas rápidamente. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**8.** El niño bebió leche antes de dormir. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]`,
      },
    },
    '3': {
      'japanese': {
        dialogue: `# 会話

## 週末にしたこと (Lo que hicimos el fin de semana)

**Carlos:** ¡Hola, Sofía! ¿Qué hiciste el fin de semana?

**Sofía:** Hola, Carlos. Yo **escribí** una carta a mi prima que **vive** en México. ¿Te gustó la que te enseñé?

**Carlos:** ¡Sí! **Escribiste** muy bien. Yo **abrí** todas las ventanas de mi habitación porque hacía calor.

**Sofía:** ¿**Abriste** también la del balcón?

**Carlos:** Sí, la **abrí** también. Después **subí** al tejado para ver las estrellas con mi hermano.

**Sofía:** ¡Qué divertido! Yo **viví** una experiencia similar cuando fui al campo.

**Carlos:** ¿**Subiste** también a un lugar alto?

**Sofía:** Sí, **subí** a una montaña pequeña. Allí **escribí** poemas sobre la naturaleza.

**Carlos:** Mis abuelos también **vivieron** en el campo cuando eran jóvenes.`,
        conjugation: `# 過去形 - 動詞 VIVIR (住む)

| yo            | viví  | nosotros/nosotras   | vivimos |
| ------------- | ----- | ------------------- | ------- |
| tú            | viviste | vosotros/vosotras   | vivisteis  |
| él/ella/usted | vivió  | ellos/ellas/ustedes | vivieron   |

**例文:** Yo viví en Barcelona cuando era pequeño.

## 正しい形で空欄を過去形で埋めてください:

**1.** Yo [SHORT_LINE] (escribir) un cuento sobre dragones ayer.

**2.** Tú [SHORT_LINE] (abrir) la puerta del jardín esta mañana.

**3.** Ella [SHORT_LINE] (subir) las escaleras corriendo.

**4.** Nosotros [SHORT_LINE] (vivir) momentos muy felices en las vacaciones.

**5.** Ellos [SHORT_LINE] (escribir) cartas a sus familias.

**6.** Vosotros [SHORT_LINE] (abrir) los regalos en la fiesta.

**7.** Usted [SHORT_LINE] (subir) al autobús en la parada de la esquina.

**8.** Mis primas [SHORT_LINE] (vivir) una aventura increíble en el bosque.

**9.** Tú [SHORT_LINE] (escribir) tu nombre en la pizarra de la clase.

**10.** Nosotras [SHORT_LINE] (abrir) todas las ventanas.`,
        choice: `# 正しい選択肢を選んで完全な文を書いてください:

**1.** Elena [vivió | vivieron] en París durante dos años.

[LONG_LINE]

**2.** Los estudiantes [escribió | escribieron] poemas en la clase de literatura.

[LONG_LINE]

**3.** Roberto [abrió | abrieron] el libro por la página correcta.

[LONG_LINE]

**4.** Nosotros [subimos | subió] la montaña muy temprano.

[LONG_LINE]

**5.** Carmen [viviste | vivió] experiencias únicas en su viaje.

[LONG_LINE]

**6.** Vosotros [escribisteis | escribieron] mensajes a vuestros amigos.

[LONG_LINE]

**7.** El portero [abrió | abrieron] la puerta del edificio para nosotros.

[LONG_LINE]

**8.** Tú [subiste | subió] corriendo las escaleras del colegio.

[LONG_LINE]`,
        transformation: `# 指示に従って動詞の人称を変えてください:

**1.** Yo escribí → Nosotros [SHORT_LINE]

**2.** Tú abriste → Él [SHORT_LINE]

**3.** Ella vivió → Ellas [SHORT_LINE]

**4.** Nosotros subimos → Yo [SHORT_LINE]

**5.** Vosotros escribisteis → Tú [SHORT_LINE]

**6.** Él abrió → Nosotros [SHORT_LINE]

**7.** Ellas vivieron → Ella [SHORT_LINE]

**8.** Yo subí → Vosotros [SHORT_LINE]

## 質問に答えてください:

**1.** ¿Tú escribiste una carta? → Sí, yo [SHORT_LINE] una carta.

**2.** ¿Ellos abrieron la puerta? → Sí, ellos [SHORT_LINE] la puerta.

**3.** ¿Vosotros vivisteis en Madrid? → Sí, nosotros [SHORT_LINE] en Madrid.

**4.** ¿Ella subió las escaleras? → Sí, ella [SHORT_LINE] las escaleras.

**5.** ¿Ustedes escribieron los ejercicios? → Sí, nosotros [SHORT_LINE] los ejercicios.`,
        ordering: `# 単語を正しい順番に並べて文を完成させてください:

**1.** [ayer / escribió / Carmen / una / historia / interesante]
昨日カルメンは面白い話を書きました

[LONG_TALL_LINE]

**2.** [puerta / abrimos / la / del / jardín / Nosotros]
私たちは庭の扉を開けました

[LONG_TALL_LINE]

**3.** [vivieron / Mis / abuelos / en / el / pueblo / muchos / años]
私の祖父母は村に長年住んでいました

[LONG_TALL_LINE]

**4.** [montaña / subiste / Tú / la / con / tus / amigos]
あなたは友達と山に登りました

[LONG_TALL_LINE]

**5.** [Los / estudiantes / escribieron / cartas / a / sus / familias]
学生たちは家族に手紙を書きました

[LONG_TALL_LINE]

**6.** [ventana / abrió / la / María / para / ver / el / jardín]
マリアは庭を見るために窓を開けました

[LONG_TALL_LINE]`,
        evaluation: `# 文が正しければB（bien）、間違っていればM（mal）を書いてください:

**1.** Mi familia vivió en Chile durante cinco años. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**2.** Los niños escribió cuentos muy creativos. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**3.** Nosotros subimos al segundo piso del museo. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**4.** Tú abriste la caja con mucho cuidado. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**5.** Ana y Luis vivieron aventuras emocionantes. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**6.** Yo escribí una postal a mi hermana mayor. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**7.** Vosotros abrió las maletas al llegar al hotel. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**8.** El gato subió al árbol para escapar del perro. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]`,
      },
      'english': {
        dialogue: `# Dialogue

## What we did over the weekend

**Carlos:** ¡Hola, Sofía! ¿Qué hiciste el fin de semana?

**Sofía:** Hola, Carlos. Yo **escribí** una carta a mi prima que **vive** en México. ¿Te gustó la que te enseñé?

**Carlos:** ¡Sí! **Escribiste** muy bien. Yo **abrí** todas las ventanas de mi habitación porque hacía calor.

**Sofía:** ¿**Abriste** también la del balcón?

**Carlos:** Sí, la **abrí** también. Después **subí** al tejado para ver las estrellas con mi hermano.

**Sofía:** ¡Qué divertido! Yo **viví** una experiencia similar cuando fui al campo.

**Carlos:** ¿**Subiste** también a un lugar alto?

**Sofía:** Sí, **subí** a una montaña pequeña. Allí **escribí** poemas sobre la naturaleza.

**Carlos:** Mis abuelos también **vivieron** en el campo cuando eran jóvenes.`,
        conjugation: `# Past tense - Verb VIVIR (to live)

| yo            | viví  | nosotros/nosotras   | vivimos |
| ------------- | ----- | ------------------- | ------- |
| tú            | viviste | vosotros/vosotras   | vivisteis  |
| él/ella/usted | vivió  | ellos/ellas/ustedes | vivieron   |

**Example:** Yo viví en Barcelona cuando era pequeño.

## Fill in the blanks with the correct past tense form:

**1.** Yo [SHORT_LINE] (escribir) un cuento sobre dragones ayer.

**2.** Tú [SHORT_LINE] (abrir) la puerta del jardín esta mañana.

**3.** Ella [SHORT_LINE] (subir) las escaleras corriendo.

**4.** Nosotros [SHORT_LINE] (vivir) momentos muy felices en las vacaciones.

**5.** Ellos [SHORT_LINE] (escribir) cartas a sus familias.

**6.** Vosotros [SHORT_LINE] (abrir) los regalos en la fiesta.

**7.** Usted [SHORT_LINE] (subir) al autobús en la parada de la esquina.

**8.** Mis primas [SHORT_LINE] (vivir) una aventura increíble en el bosque.

**9.** Tú [SHORT_LINE] (escribir) tu nombre en la pizarra de la clase.

**10.** Nosotras [SHORT_LINE] (abrir) todas las ventanas.`,
        choice: `# Choose the correct option and write the complete sentence:

**1.** Elena [vivió | vivieron] en París durante dos años.

[LONG_LINE]

**2.** Los estudiantes [escribió | escribieron] poemas en la clase de literatura.

[LONG_LINE]

**3.** Roberto [abrió | abrieron] el libro por la página correcta.

[LONG_LINE]

**4.** Nosotros [subimos | subió] la montaña muy temprano.

[LONG_LINE]

**5.** Carmen [viviste | vivió] experiencias únicas en su viaje.

[LONG_LINE]

**6.** Vosotros [escribisteis | escribieron] mensajes a vuestros amigos.

[LONG_LINE]

**7.** El portero [abrió | abrieron] la puerta del edificio para nosotros.

[LONG_LINE]

**8.** Tú [subiste | subió] corriendo las escaleras del colegio.

[LONG_LINE]`,
        transformation: `# Change the person as instructed:

**1.** Yo escribí → Nosotros [SHORT_LINE]

**2.** Tú abriste → Él [SHORT_LINE]

**3.** Ella vivió → Ellas [SHORT_LINE]

**4.** Nosotros subimos → Yo [SHORT_LINE]

**5.** Vosotros escribisteis → Tú [SHORT_LINE]

**6.** Él abrió → Nosotros [SHORT_LINE]

**7.** Ellas vivieron → Ella [SHORT_LINE]

**8.** Yo subí → Vosotros [SHORT_LINE]

## Answer the questions:

**1.** ¿Tú escribiste una carta? → Sí, yo [SHORT_LINE] una carta.

**2.** ¿Ellos abrieron la puerta? → Sí, ellos [SHORT_LINE] la puerta.

**3.** ¿Vosotros vivisteis en Madrid? → Sí, nosotros [SHORT_LINE] en Madrid.

**4.** ¿Ella subió las escaleras? → Sí, ella [SHORT_LINE] las escaleras.

**5.** ¿Ustedes escribieron los ejercicios? → Sí, nosotros [SHORT_LINE] los ejercicios.`,
        ordering: `# Put the words in the correct order to complete the sentence:

**1.** [ayer / escribió / Carmen / una / historia / interesante]
Yesterday Carmen wrote an interesting story

[LONG_TALL_LINE]

**2.** [puerta / abrimos / la / del / jardín / Nosotros]
We opened the garden door

[LONG_TALL_LINE]

**3.** [vivieron / Mis / abuelos / en / el / pueblo / muchos / años]
My grandparents lived in the village for many years

[LONG_TALL_LINE]

**4.** [montaña / subiste / Tú / la / con / tus / amigos]
You climbed the mountain with your friends

[LONG_TALL_LINE]

**5.** [Los / estudiantes / escribieron / cartas / a / sus / familias]
The students wrote letters to their families

[LONG_TALL_LINE]

**6.** [ventana / abrió / la / María / para / ver / el / jardín]
María opened the window to see the garden

[LONG_TALL_LINE]`,
        evaluation: `# Write B (bien) if the sentence is correct, M (mal) if it's wrong:

**1.** Mi familia vivió en Chile durante cinco años. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**2.** Los niños escribió cuentos muy creativos. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**3.** Nosotros subimos al segundo piso del museo. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**4.** Tú abriste la caja con mucho cuidado. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**5.** Ana y Luis vivieron aventuras emocionantes. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**6.** Yo escribí una postal a mi hermana mayor. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**7.** Vosotros abrió las maletas al llegar al hotel. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**8.** El gato subió al árbol para escapar del perro. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]`,
      },
    },
    '4': {
      'japanese': {
        dialogue: `# 会話

## 昨日したこと (Lo que hicimos ayer)

**Ana:** ¡Hola Carlos! ¿Qué hiciste ayer?

**Carlos:** **Busqué** mi libro de matemáticas. ¿Tú **comiste** en el comedor de la escuela?

**Ana:** Sí, **comí** mi almuerzo allí. También **viví** una experiencia muy divertida en el recreo.

**Carlos:** ¿Qué pasó? Yo **aprendí** palabras nuevas en inglés con la profesora.

**Ana:** **Escribí** una carta a mi abuela de España. Después **leí** un cuento muy bonito.

**Carlos:** Mi familia **habló** español en la cena. ¿Tú **bebiste** algo especial?

**Ana:** **Bebí** zumo de naranja. Mi madre y yo **bailamos** en el salón después.

**Carlos:** ¡Qué divertido! Yo **dibujé** animales en mi cuaderno. Mi hermano **abrió** su libro y **subió** a su habitación.

**Ana:** Nosotros también **subimos** las escaleras para ir a la biblioteca. Allí **leímos** muchos libros interesantes.`,
        conjugation: `# 動詞の原形を見つけましょう

活用された動詞を見て、その原形を書いてください。

**例:** Ella **habló** con su mamá → 原形: **hablar**

**1.** Los niños **comieron** fruta en el recreo → [SHORT_LINE]

**2.** María **dibujó** flores en su cuaderno → [SHORT_LINE]

**3.** Nosotros **vivimos** en una casa grande → [SHORT_LINE]

**4.** Tú **buscaste** tu pelota en el jardín → [SHORT_LINE]

**5.** Ellos **abrieron** las ventanas por la mañana → [SHORT_LINE]

## 正しい形で空欄を過去形で埋めてください:

**1.** Yo [SHORT_LINE] (hablar) español con mis abuelos ayer.

**2.** Tú [SHORT_LINE] (comer) fruta en el desayuno esta mañana.

**3.** Ella [SHORT_LINE] (vivir) cerca de la estación el año pasado.

**4.** Nosotros [SHORT_LINE] (leer) libros interesantes anoche.

**5.** Ellos [SHORT_LINE] (bailar) en la fiesta de cumpleaños.

**6.** Vosotros [SHORT_LINE] (escribir) cartas a vuestros amigos.

**7.** Usted [SHORT_LINE] (beber) té todas las mañanas.

**8.** Mis hermanas [SHORT_LINE] (aprender) a tocar el piano.

**9.** Tú [SHORT_LINE] (subir) las escaleras muy rápido.

**10.** Nosotras [SHORT_LINE] (abrir) las ventanas de la clase.`,
        choice: `# 正しい選択肢を選んで完全な文を書いてください:

**1.** Ana [habló | hablaron] con su profesora después de la clase.

[LONG_LINE]

**2.** Los estudiantes [comió | comieron] en la cafetería ayer.

[LONG_LINE]

**3.** Mi familia [vivió | vivieron] momentos felices en las vacaciones.

[LONG_LINE]

**4.** Nosotros [leímos | leyó] el periódico esta mañana.

[LONG_LINE]

**5.** Carmen [bailaste | bailó] flamenco en la fiesta del colegio.

[LONG_LINE]

**6.** Vosotros [escribisteis | escribieron] poemas muy bonitos.

[LONG_LINE]

**7.** El niño [bebió | bebieron] leche antes de acostarse.

[LONG_LINE]

**8.** Tú [aprendiste | aprendió] francés el verano pasado.

[LONG_LINE]`,
        transformation: `# 指示に従って動詞の人称を変えてください:

**1.** Yo hablé → Nosotros [SHORT_LINE]

**2.** Tú comiste → Él [SHORT_LINE]

**3.** Ella vivió → Ellas [SHORT_LINE]

**4.** Nosotros leímos → Yo [SHORT_LINE]

**5.** Vosotros bailasteis → Tú [SHORT_LINE]

**6.** Él escribió → Nosotros [SHORT_LINE]

**7.** Ellas bebieron → Ella [SHORT_LINE]

**8.** Yo aprendí → Vosotros [SHORT_LINE]

## 質問に答えてください:

**1.** ¿Tú hablaste español? → Sí, yo [SHORT_LINE] español.

**2.** ¿Ellos comieron pizza? → Sí, ellos [SHORT_LINE] pizza.

**3.** ¿Vosotros vivisteis aquí? → Sí, nosotros [SHORT_LINE] aquí.

**4.** ¿Ella leyó el libro? → Sí, ella [SHORT_LINE] el libro.

**5.** ¿Ustedes bailaron mucho? → Sí, nosotros [SHORT_LINE] mucho.`,
        ordering: `# 単語を正しい順番に並べて文を完成させてください:

**1.** [ayer / habló / María / con / su / hermana / por / teléfono]
昨日マリアは電話で妹と話しました

[LONG_TALL_LINE]

**2.** [comimos / Nosotros / pizza / en / la / fiesta / anoche]
私たちは昨夜パーティーでピザを食べました

[LONG_TALL_LINE]

**3.** [vivieron / Mis / abuelos / en / el / campo / muchos / años]
私の祖父母は長年田舎に住んでいました

[LONG_TALL_LINE]

**4.** [libro / leí / interesante / Yo / un / muy / ayer]
昨日私はとても面白い本を読みました

[LONG_TALL_LINE]

**5.** [bailaron / Los / niños / en / el / patio / del / colegio]
子供たちは学校の中庭で踊りました

[LONG_TALL_LINE]

**6.** [carta / escribió / una / El / estudiante / a / su / familia]
学生は家族に手紙を書きました

[LONG_TALL_LINE]`,
        evaluation: `# 文が正しければB（bien）、間違っていればM（mal）を書いてください:

**1.** Mi hermano habló con el director ayer. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**2.** Los estudiantes comió en el comedor de la escuela. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**3.** Nosotros vivimos experiencias increíbles. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**4.** Tú leíste muchos libros durante las vacaciones. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**5.** María y Ana bailaron salsa en la fiesta. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**6.** Yo escribí un cuento sobre aventuras. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**7.** Vosotros bebió zumo de naranja en el desayuno. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]

**8.** Los niños aprendieron canciones nuevas en música. [ONE_LETTER_LINE]

   訂正: [LONG_LINE]`,
      },
      'english': {
        dialogue: `# Dialogue

## What we did yesterday

**Ana:** ¡Hola Carlos! ¿Qué hiciste ayer?

**Carlos:** **Busqué** mi libro de matemáticas. ¿Tú **comiste** en el comedor de la escuela?

**Ana:** Sí, **comí** mi almuerzo allí. También **viví** una experiencia muy divertida en el recreo.

**Carlos:** ¿Qué pasó? Yo **aprendí** palabras nuevas en inglés con la profesora.

**Ana:** **Escribí** una carta a mi abuela de España. Después **leí** un cuento muy bonito.

**Carlos:** Mi familia **habló** español en la cena. ¿Tú **bebiste** algo especial?

**Ana:** **Bebí** zumo de naranja. Mi madre y yo **bailamos** en el salón después.

**Carlos:** ¡Qué divertido! Yo **dibujé** animales en mi cuaderno. Mi hermano **abrió** su libro y **subió** a su habitación.

**Ana:** Nosotros también **subimos** las escaleras para ir a la biblioteca. Allí **leímos** muchos libros interesantes.`,
        conjugation: `# Find the infinitive form of the verbs

Look at the conjugated verbs and write their infinitive form.

**Example:** Ella **habló** con su mamá → Infinitive: **hablar**

**1.** Los niños **comieron** fruta en el recreo → [SHORT_LINE]

**2.** María **dibujó** flores en su cuaderno → [SHORT_LINE]

**3.** Nosotros **vivimos** en una casa grande → [SHORT_LINE]

**4.** Tú **buscaste** tu pelota en el jardín → [SHORT_LINE]

**5.** Ellos **abrieron** las ventanas por la mañana → [SHORT_LINE]

## Fill in the blanks with the correct past tense form:

**1.** Yo [SHORT_LINE] (hablar) español con mis abuelos ayer.

**2.** Tú [SHORT_LINE] (comer) fruta en el desayuno esta mañana.

**3.** Ella [SHORT_LINE] (vivir) cerca de la estación el año pasado.

**4.** Nosotros [SHORT_LINE] (leer) libros interesantes anoche.

**5.** Ellos [SHORT_LINE] (bailar) en la fiesta de cumpleaños.

**6.** Vosotros [SHORT_LINE] (escribir) cartas a vuestros amigos.

**7.** Usted [SHORT_LINE] (beber) té todas las mañanas.

**8.** Mis hermanas [SHORT_LINE] (aprender) a tocar el piano.

**9.** Tú [SHORT_LINE] (subir) las escaleras muy rápido.

**10.** Nosotras [SHORT_LINE] (abrir) las ventanas de la clase.`,
        choice: `# Choose the correct option and write the complete sentence:

**1.** Ana [habló | hablaron] con su profesora después de la clase.

[LONG_LINE]

**2.** Los estudiantes [comió | comieron] en la cafetería ayer.

[LONG_LINE]

**3.** Mi familia [vivió | vivieron] momentos felices en las vacaciones.

[LONG_LINE]

**4.** Nosotros [leímos | leyó] el periódico esta mañana.

[LONG_LINE]

**5.** Carmen [bailaste | bailó] flamenco en la fiesta del colegio.

[LONG_LINE]

**6.** Vosotros [escribisteis | escribieron] poemas muy bonitos.

[LONG_LINE]

**7.** El niño [bebió | bebieron] leche antes de acostarse.

[LONG_LINE]

**8.** Tú [aprendiste | aprendió] francés el verano pasado.

[LONG_LINE]`,
        transformation: `# Change the person as instructed:

**1.** Yo hablé → Nosotros [SHORT_LINE]

**2.** Tú comiste → Él [SHORT_LINE]

**3.** Ella vivió → Ellas [SHORT_LINE]

**4.** Nosotros leímos → Yo [SHORT_LINE]

**5.** Vosotros bailasteis → Tú [SHORT_LINE]

**6.** Él escribió → Nosotros [SHORT_LINE]

**7.** Ellas bebieron → Ella [SHORT_LINE]

**8.** Yo aprendí → Vosotros [SHORT_LINE]

## Answer the questions:

**1.** ¿Tú hablaste español? → Sí, yo [SHORT_LINE] español.

**2.** ¿Ellos comieron pizza? → Sí, ellos [SHORT_LINE] pizza.

**3.** ¿Vosotros vivisteis aquí? → Sí, nosotros [SHORT_LINE] aquí.

**4.** ¿Ella leyó el libro? → Sí, ella [SHORT_LINE] el libro.

**5.** ¿Ustedes bailaron mucho? → Sí, nosotros [SHORT_LINE] mucho.`,
        ordering: `# Put the words in the correct order to complete the sentence:

**1.** [ayer / habló / María / con / su / hermana / por / teléfono]
Yesterday María talked to her sister on the phone

[LONG_TALL_LINE]

**2.** [comimos / Nosotros / pizza / en / la / fiesta / anoche]
We ate pizza at the party last night

[LONG_TALL_LINE]

**3.** [vivieron / Mis / abuelos / en / el / campo / muchos / años]
My grandparents lived in the countryside for many years

[LONG_TALL_LINE]

**4.** [libro / leí / interesante / Yo / un / muy / ayer]
Yesterday I read a very interesting book

[LONG_TALL_LINE]

**5.** [bailaron / Los / niños / en / el / patio / del / colegio]
The children danced in the school courtyard

[LONG_TALL_LINE]

**6.** [carta / escribió / una / El / estudiante / a / su / familia]
The student wrote a letter to his family

[LONG_TALL_LINE]`,
        evaluation: `# Write B (bien) if the sentence is correct, M (mal) if it's wrong:

**1.** Mi hermano habló con el director ayer. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**2.** Los estudiantes comió en el comedor de la escuela. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**3.** Nosotros vivimos experiencias increíbles. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**4.** Tú leíste muchos libros durante las vacaciones. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**5.** María y Ana bailaron salsa en la fiesta. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**6.** Yo escribí un cuento sobre aventuras. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**7.** Vosotros bebió zumo de naranja en el desayuno. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]

**8.** Los niños aprendieron canciones nuevas en música. [ONE_LETTER_LINE]

   Correction: [LONG_LINE]`,
      },
    },
  },
};
